### PR TITLE
Remove files, generated by dvipng.

### PR DESCRIPTION
**Pull request by hpreusse**
I notice that during build the program dvipng is called. After installing the Debian package and rebuilding I noticed that some files are not removed even by dist-clean. Consider the pull request.

### CODE REVIEW

**Comment by stloeffler** [comment]
Interesting - this doesn't seem to happen on my system... Thanks for the PR!
Curiously, `dvipng` does not seem to be mentioned in the repository anywhere - I assume it is called automatically "under the hood" by your tex4ht installation.

Could you please tell me
* how many `index*.png` files are produced (roughly); btw, I would prefer `index*.png` over `index*png` in the PR
* what do they contain? single "special" characters/symbols, true figures, or something else....
* What TeX distro are you using (and where did you get it from; e.g. Debian-packaged texlive, manually installed texlive, ...)?

**Comment by hpreusse** [comment]
> Curiously, `dvipng` does not seem to be mentioned in the repository anywhere - I assume it is called automatically "under the hood" by your tex4ht installation.
> 
Thats what I guess too, as I didn't found the string "dvipng" in the source tree.

>     * how many `index*.png` files are produced (roughly); btw, I would prefer `index*.png` over `index*png` in the PR
> 
index0x.png...index8x.png each for french and english.

>     * what do they contain? single "special" characters/symbols, true figures, or something else....
> 
They contain just arrows, files atached. [png.zip](https://github.com/TeXworks/manual/files/6329417/png.zip)

>     * What TeX distro are you using (and where did you get it from; e.g. Debian-packaged texlive, manually installed texlive, ...)?
> 
I'm packaging the texworks-manual for Debian, see [our repository](https://github.com/debian-tex/texworks-manual).

**Comment by hpreusse** [comment]
> Interesting - this doesn't seem to happen on my system... Thanks for the PR!
> Curiously, `dvipng` does not seem to be mentioned in the repository anywhere - I assume it is called automatically "under the hood" by your tex4ht installation.
> 
I noticed that dvipng is only called, if the patch for #8 is applied, which includes a removal of the `tex4ht.env` files. Not sure why these files are there, but using dvipng to convert dvi to png, seems to be more effective to me than "dvips -> gs -> convert", which is currently used.
Further: if the `tex4ht.env` files exists, these index...png files are created in subdir `images`, which is removed by the Makefile in subdir `html`.

**Comment by stloeffler** [comment]
Closing as this has been superseded by #11

**Pull request closed without merging**
